// Auth Constants
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Member Constants
export const ADD_MEMBER = 'ADD_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_MEMBER_PAYMENT_STATUS = 'UPDATE_MEMBER_PAYMENT_STATUS';
export const SET_TARGET_PAYMENT = 'SET_TARGET_PAYMENT';

// Transaction Constants
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';

// Settings Constants
export const UPDATE_PAYMENT_METHODS = 'UPDATE_PAYMENT_METHODS';
export const UPDATE_CLASS_INFO = 'UPDATE_CLASS_INFO'; 